# Generated by Django 3.1.3 on 2020-11-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('option', models.CharField(max_length=10)),
                ('mul_option', models.CharField(max_length=10)),
            ],
        ),
    ]
