# Generated by Django 3.1.3 on 2020-11-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
